include: package:pedantic/analysis_options.yaml

linter:
  rules:
    - camel_case_types
    - avoid_print

analyzer:
  enable-experiment:
    - non-nullable
  errors:
    todo: ignore
  exclude:
    - example/main.dart